[init-tracing]
service-name           = "hello-tonic-server"
otlp-exporter-endpoint = "http://localhost:4317"
sampling-probability   = 0.5

[server]
addr         = "0.0.0.0"
port         = 80
delay-millis = 50
